### ISSUE TITLE
Add Jest and tests

### ISSUE THREAD

**Issue by vutran** [vutran/dext-hackernews-plugin#3]
For consistency with the [`dext`](https://github.com/vutran/dext) project, we should use [`jest`](https://github.com/facebook/jest) as our choice of testing framework.

**Comment by singh1114** [comment]
ok.

**Comment by iswanj** [comment]
@singh1114 Are you working on this?

**Comment by singh1114** [comment]
@iswanj No, If you want to you can..

**Comment by iswanj** [comment]
@vutran I'll take this :+1:

**Comment by vutran** [comment]
@iswanj Go ahead.

**Comment by vutran** [comment]
Merged #7
